/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ovr_OculusRift */

#ifndef _Included_tools3d_ovr_OculusRift
#define _Included_tools3d_ovr_OculusRift
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_tools3d_ovr_OculusRift03__1initSubsystem(JNIEnv *env, jobject jobj) ;

JNIEXPORT void JNICALL Java_tools3d_ovr_OculusRift03__1destroySubsystem(JNIEnv *env, jobject jobj);

JNIEXPORT void JNICALL Java_tools3d_ovr_OculusRift03__1pollSubsystem(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_tools3d_ovr_OculusRift03__1pollSubsystemDT(JNIEnv *, jobject, jfloat dt);

JNIEXPORT jfloat JNICALL Java_tools3d_ovr_OculusRift03__1getYaw(JNIEnv *, jobject);

JNIEXPORT jfloat JNICALL Java_tools3d_ovr_OculusRift03__1getPitch(JNIEnv *, jobject);

JNIEXPORT jfloat JNICALL Java_tools3d_ovr_OculusRift03__1getRoll(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_tools3d_ovr_OculusRift03__1reset(JNIEnv *, jobject) ;

JNIEXPORT jobject JNICALL Java_tools3d_ovr_OculusRift03__1getHmdDesc(JNIEnv *env, jobject thisObj );

#ifdef __cplusplus
}
#endif
#endif
